name: Cekat AI to BigQuery ETL

on:
  schedule:
    # Berjalan harian setiap jam 19:00 UTC (02:00 WIB)
    - cron: '39 19 * * *'
  workflow_dispatch: # Supaya bisa di-klik manual untuk testing

jobs:
  run-cekat-pipeline:
    runs-on: ubuntu-latest

    # 🌟 TAMBAHKAN BLOK ENV DI SINI (Level Job)
    env:
      CEKAT_API_KEY: ${{ secrets.CEKAT_API_KEY }}

    steps:
    # 1. Checkout kode dari repositori
    - name: Checkout Repository Kode
      uses: actions/checkout@v4

    # 2. Setup Python environment
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 3. Install semua dependensi library (DITAMBAHKAN NUMPY)
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas pyarrow python-dateutil google-cloud-bigquery numpy

    # 4. Melakukan autentikasi ke Google Cloud menggunakan Secret
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # 5. Jalankan ETL Cekat Pertama: Boards Tracker Skin & Slim
    - name: Run Cekat Boards Tracker Script
      run: python etl_boards_tracker_skin_slim.py

    # 6. Jalankan ETL Cekat Kedua: All Boards Cekat
    - name: Run All Boards Cekat Script
      run: python etl_all_boards_cekat.py

    # 7. Jalankan ETL Cekat Ketiga: Boards Calendar Cekat
    - name: Run Boards Calendar Cekat Script
      run: python etl_boards_calendar_cekat.py

    # 8. Jalankan ETL Cekat Keempat: Conversation Cekat
    - name: Run Conversation Cekat Script
      run: python etl_conversation_cekat.py

    # 7. Jalankan ETL Cekat Kelima: Boards Calendar Cekat
    - name: Run Messages Cekat Script
      run: python etl_messages_cekat_ads.py
